# Generated by Django 3.2.11 on 2022-01-13 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votacionApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrio',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='votacionApi.municipio', verbose_name='Municipio'),
            preserve_default=False,
        ),
    ]
