# Generated by Django 3.2.11 on 2022-01-13 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votacionApi', '0002_barrio_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('identificacion', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.TextField()),
                ('rol', models.PositiveIntegerField(choices=[(1, 'ADMINISTRADOR'), (2, 'LIDER')])),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='votacionApi.barrio', verbose_name='Barrio')),
            ],
        ),
    ]
