# Generated by Django 3.2.11 on 2022-01-14 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votacionApi', '0003_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lider',
            name='barrio',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
        migrations.AddField(
            model_name='users',
            name='latitud',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='longitud',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='votante',
            name='lider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='votacionApi.users', verbose_name='Lider'),
        ),
        migrations.DeleteModel(
            name='Lider',
        ),
    ]
