# Generated by Django 3.2.11 on 2022-01-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacionApi', '0004_auto_20220114_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='puestovotacion',
            name='latitud',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puestovotacion',
            name='longitud',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
