# Generated by Django 3.2.11 on 2022-01-14 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('votacionApi', '0006_auto_20220114_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uuarios',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('identificacion', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('rol', models.PositiveIntegerField(choices=[(1, 'ADMINISTRADOR'), (2, 'LIDER')])),
                ('latitud', models.CharField(max_length=200)),
                ('longitud', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
