# Generated by Django 3.2.11 on 2022-01-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votacionApi', '0007_uuarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
    ]
