# Generated by Django 3.2.11 on 2022-01-14 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votacionApi', '0008_alter_users_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
