# Generated by Django 3.2.11 on 2022-01-14 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votacionApi', '0009_alter_users_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uuarios',
        ),
    ]
