# Generated by Django 3.2.11 on 2022-01-14 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votacionApi', '0010_delete_uuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='votacionApi.departamento', verbose_name='Departamento'),
        ),
    ]
