# Generated by Django 3.2.11 on 2022-01-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacionApi', '0011_alter_municipio_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
